version: '3.11'

services:
  microservice:
    build:
      context: ./microservice
    image: simple-microservice
    container_name: simple-microservice
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: gunicorn -b 127.0.0.1:8000 -k uvicorn.workers.UvicornWorker simple-microservice:api
