version: '3.8'

services:
  microservice:
    build:
      context: ./microservice
    image: async-few-threads-microservice
    container_name: async-few-threads-microservice
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: gunicorn -b 127.0.0.1:8000 -workers=3 -k uvicorn.workers.UvicornWorker async-few-threads-microservice:api
